- hosts: web
  become: yes
  tasks:
  - name: "install nginx"
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: "create www directory"
    ansible.builtin.file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'

  - name: delete default nginx site
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: "copy custom config"
    ansible.builtin.copy:
      src: ./config/nginx.conf
      dest: /etc/nginx/
    notify: restart nginx

  - name: copy nginx site.conf
    ansible.builtin.template:
      src: ./config/templates/site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: "copy website"
    ansible.builtin.copy:
      src: ./config/site/
      dest: /var/www/{{ domain }}
        
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
